// ORQUESTRA DEV 0.3 | Browser layer. No privileged credentials, shell, or production actions.
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const safe=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const uid=()=>globalThis.crypto?.randomUUID?.()||`demo-${Date.now()}`;
const config=window.ORQ_CONFIG||{};
const configured=/^https:\/\/[a-z0-9.-]+$/i.test(config.supabaseUrl||'')&&!!config.supabasePublishableKey&&!(config.supabaseUrl||'').includes('SEU-PROJETO');
const demoKey='orquestra-dev-demo-v03';
const starter={projects:[{id:'demo-project-a',name:'Projeto Alpha',repo_url:'https://github.com/example/project-alpha',created_at:'2026-10-06T12:00:00Z'},{id:'demo-project-b',name:'Interface Studio',repo_url:'',created_at:'2026-10-07T12:00:00Z'}],nodes:[{id:'demo-node',name:'Executor de exemplo',last_seen_at:null,revoked_at:null}],tasks:[{id:'task-demo-a',title:'Analisar fluxo de autenticação',project_id:'demo-project-a',kind:'diagnose',status:'completed',output:'Exemplo de relatório ilustrativo, não executado por um agente real.',created_at:'2026-10-07T12:00:00Z'},{id:'task-demo-b',title:'Revisar componentes do dashboard',project_id:'demo-project-b',kind:'codex',status:'queued',created_at:'2026-10-08T10:00:00Z'}]};
let db=null, mode='off', state={projects:[],nodes:[],tasks:[]}, taskFilter='all', toastTimeout;
const pages={overview:['Overview','Command center'],create:['Nova missão','Create operation'],missions:['Missões','Execution pipeline'],projects:['Repositórios','Codebase inventory'],nodes:['Executores','Device registry'],connections:['Integrações','Provider connectivity'],settings:['Configurações','System settings']};
const demoRead=()=>{try{const result=JSON.parse(localStorage.getItem(demoKey));return result&&Array.isArray(result.projects)&&Array.isArray(result.tasks)&&Array.isArray(result.nodes)?result:structuredClone(starter)}catch{return structuredClone(starter)}};
const demoSave=()=>{if(mode==='demo')localStorage.setItem(demoKey,JSON.stringify(state))};
function notify(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.hidden=true,4200)}
function showMode(){const isDemo=mode==='demo', logged=mode==='live'; $('#setup').hidden=mode!=='off';$('#auth').hidden=mode!=='auth';$('#app').hidden=!isDemo&&!logged;$('#demoBanner').hidden=!isDemo;$('#logout').hidden=!logged;$('#settingsExitDemo').hidden=!isDemo;$('#settingsMode').textContent=isDemo?'Demonstração local — não sincronizado':logged?'Autenticado no Supabase':'Não configurado';$('#settingsTag').textContent=isDemo?'DEMO':logged?'ONLINE':'PENDING';$('#sideDot').classList.toggle('on',logged);$('#sideConnection').textContent=logged?'SUPABASE CONNECTED':isDemo?'DEMO SESSION':'NO BACKEND';$('#sideMessage').textContent=logged?'Autenticado':isDemo?'Ambiente ilustrativo':'Configuração pendente';$('#terminalDb').textContent=logged?'Supabase conectado':isDemo?'demonstração local ativa':'backend não configurado';$('#supabaseConnection').textContent=logged?'AUTENTICADO / ISOLADO':isDemo?'DEMO / NÃO CONECTADO':'NÃO CONFIGURADO';$('#networkDot').classList.toggle('on',false);}
function page(name){if(!pages[name]||($('#app').hidden))return;$$('.page').forEach(e=>e.hidden=e.id!==name);$$('.nav-link').forEach(e=>e.classList.toggle('active',e.dataset.target===name));$('#breadcrumb').textContent=pages[name][0];window.scrollTo({top:0,behavior:'smooth'});}
function startDemo(){mode='demo';state=demoRead();showMode();render();page('overview');notify('Modo de demonstração — nenhuma tarefa será executada.');}
function exitDemo(){mode='off';showMode();$('#breadcrumb').textContent='Setup';}
function getNodeOnline(n){return !n.revoked_at&&n.last_seen_at&&(Date.now()-Date.parse(n.last_seen_at))<90000}
function statusLabel(s){return ({queued:'NA FILA',running:'EXECUTANDO',completed:'CONCLUÍDA',failed:'FALHOU',cancelled:'CANCELADA'})[s]||String(s||'').toUpperCase()}
function kindLabel(s){return ({diagnose:'DIAGNOSE',integrations:'INTEGRATIONS',codex:'CODEX'})[s]||s}
function when(date){if(!date)return'AGUARDANDO';try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(date))}catch{return '—'}}
function renderTasks(items){if(!items.length)return '<div class="empty">Nenhuma missão encontrada. Comece criando a primeira tarefa.</div>';return items.map(t=>{const project=state.projects.find(p=>p.id===t.project_id)?.name||'Projeto';return `<div class="mission"><div class="mission-icon">${t.kind==='codex'?'⌘':t.kind==='integrations'?'⬡':'⌁'}</div><div class="mission-main"><b>${safe(t.title)}</b><small>${safe(project)}  /  ${safe(kindLabel(t.kind))}  /  ${safe(when(t.created_at))}</small>${t.output?`<details class="mission-report"><summary>VER RELATÓRIO ↗</summary><pre>${safe(t.output)}</pre></details>`:''}</div><span class="state-badge ${safe(t.status)}">${safe(statusLabel(t.status))}</span></div>`}).join('')}
function render(){const {projects,nodes,tasks}=state;$('#nProjects').textContent=projects.length;$('#nQueued').textContent=tasks.filter(t=>t.status==='queued').length;$('#nRunning').textContent=tasks.filter(t=>t.status==='running').length;$('#nCompleted').textContent=tasks.filter(t=>t.status==='completed').length;$('#navTasksCount').textContent=tasks.length;$('#projectCount').textContent=projects.length+' TOTAL';$('#nodeCount').textContent=nodes.length+' DEVICES';$('#taskProject').innerHTML=projects.length?projects.map(p=>`<option value="${safe(p.id)}">${safe(p.name)}</option>`).join(''):'<option value="">Cadastre um repositório primeiro</option>';$('#taskNode').innerHTML='<option value="">Qualquer executor autorizado</option>'+nodes.filter(n=>!n.revoked_at).map(n=>`<option value="${safe(n.id)}">${safe(n.name)}</option>`).join('');$('#tasksList').innerHTML=renderTasks(tasks.slice(0,4));$('#missionsList').innerHTML=renderTasks(tasks.filter(t=>taskFilter==='all'||t.status===taskFilter));$('#projectsList').innerHTML=projects.length?projects.map(p=>`<div class="item"><div><strong>▧ ${safe(p.name)}</strong><small>${safe(p.repo_url||'Sem URL remota cadastrada')}</small></div><code>${safe(p.id)}</code></div>`).join(''):'<div class="empty">Nenhum repositório cadastrado.</div>';$('#nodesList').innerHTML=nodes.length?nodes.map(n=>`<div class="item"><div><strong>⌁ ${safe(n.name)}</strong><small>${n.revoked_at?'REVOGADO':getNodeOnline(n)?'ONLINE':n.last_seen_at?'ÚLTIMO CONTATO '+safe(when(n.last_seen_at)):'AGUARDANDO PRIMEIRO CONTATO'}</small></div><span class="state-badge ${getNodeOnline(n)?'completed':'queued'}">${getNodeOnline(n)?'ONLINE':'OFFLINE'}</span></div>`).join(''):'<div class="empty">Nenhum executor registrado.</div>';const online=nodes.filter(getNodeOnline).length;$('#terminalNode').textContent=online?`${online} executor(es) disponíveis`:'nenhum executor online';$('#networkText').textContent=online?`${online} executor(es) conectados`:'Nenhum executor conectado';}
async function refresh(){if(mode!=='live'||!db)return;try{const [p,n,t]=await Promise.all([db.from('orq_projects').select('id,name,repo_url,created_at').order('created_at',{ascending:false}),db.from('orq_nodes').select('id,name,last_seen_at,revoked_at').order('created_at',{ascending:false}),db.from('orq_tasks').select('id,project_id,title,kind,status,output,created_at,started_at,finished_at,node_id').order('created_at',{ascending:false}).limit(100)]);if(p.error||n.error||t.error)throw p.error||n.error||t.error;state={projects:p.data||[],nodes:n.data||[],tasks:t.data||[]};render();}catch(error){console.error('refresh failed',error);notify('Não foi possível sincronizar: verifique RLS e a conexão.')}}
async function init(){showMode();$('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' BRT';setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' BRT'},1000);if(!configured){mode='off';showMode();$('#breadcrumb').textContent='Setup';return}try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.57.0');db=createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{autoRefreshToken:true,persistSession:true}});const {data:{session},error}=await db.auth.getSession();if(error)throw error;mode=session?'live':'auth';showMode();if(session){await refresh();page('overview')}db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'||event==='SIGNED_OUT'){mode=session?'live':'auth';showMode();if(session)setTimeout(()=>{refresh();page('overview')},0)}})}catch(error){console.error(error);mode='off';showMode();notify('Falha ao carregar cliente Supabase. Você ainda pode explorar a demonstração.')}}
$$('[data-goto], [data-target]').forEach(el=>el.addEventListener('click',()=>page(el.dataset.goto||el.dataset.target)));
$('#refresh').addEventListener('click',()=>{if(mode==='live')refresh();else notify('Demo: não há serviço remoto para sincronizar.')});
$('#logout').addEventListener('click',()=>db?.auth.signOut());
$('#profileToggle').addEventListener('click',()=>{if(mode==='off')return;page('settings')});
$('#startDemo').addEventListener('click',startDemo);$('#exitDemo').addEventListener('click',exitDemo);$('#settingsExitDemo').addEventListener('click',exitDemo);
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';if(!db)return;const d=new FormData(e.target);const {error}=await db.auth.signInWithPassword({email:String(d.get('email')),password:String(d.get('password'))});if(error)$('#loginError').textContent='Não foi possível entrar. Confira email e senha.'});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();$('#projectError').textContent='';const d=new FormData(e.target);const data={name:String(d.get('name')||'').trim(),repo_url:String(d.get('repo_url')||'').trim()};if(!data.name){$('#projectError').textContent='Informe um nome válido.';return}if(data.repo_url&&!/^https:\/\/github\.com\/[^/]+\/[^/]+\/?$/i.test(data.repo_url)){$('#projectError').textContent='Use uma URL de repositório GitHub válida.';return}if(mode==='demo'){state.projects.unshift({...data,id:uid(),created_at:new Date().toISOString()});demoSave();render();e.target.reset();notify('Repositório adicionado à demonstração.');return}if(mode!=='live'||!db)return;const {error}=await db.from('orq_projects').insert(data);if(error){$('#projectError').textContent='Falha ao salvar: '+error.message;return}e.target.reset();await refresh();notify('Repositório cadastrado.')});
$('#taskForm').addEventListener('submit',async e=>{e.preventDefault();$('#taskError').textContent='';const d=new FormData(e.target);const data={project_id:$('#taskProject').value,title:String(d.get('title')||'').trim(),kind:String(d.get('kind')||'diagnose'),instructions:String(d.get('instructions')||'').trim()};if(!data.project_id){$('#taskError').textContent='Cadastre um repositório primeiro.';return}if(data.instructions.length<5){$('#taskError').textContent='Descreva o objetivo e critérios de aceite.';return}if($('#taskNode').value)data.preferred_node_id=$('#taskNode').value;if(mode==='demo'){state.tasks.unshift({...data,id:uid(),status:'queued',created_at:new Date().toISOString()});demoSave();render();e.target.reset();page('missions');notify('Missão salva apenas nesta demonstração; não será executada.');return}if(mode!=='live'||!db)return;const {error}=await db.from('orq_tasks').insert(data);if(error){$('#taskError').textContent='Falha ao criar missão: '+error.message;return}e.target.reset();await refresh();page('missions');notify('Missão enviada à fila.')});
$('#nodeForm').addEventListener('submit',async e=>{e.preventDefault();$('#nodeError').textContent='';$('#pairResult').hidden=true;if(mode==='demo'){$('#nodeError').textContent='Pareamento real requer backend configurado. Nenhum segredo fictício será criado.';return}if(mode!=='live'||!db)return;const {data:{session}}=await db.auth.getSession();if(!session){$('#nodeError').textContent='Faça login novamente.';return}const d=new FormData(e.target);try{const response=await fetch(config.supabaseUrl+'/functions/v1/orq-worker',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':config.supabasePublishableKey},body:JSON.stringify({action:'register',name:String(d.get('name')||'').trim()})});const result=await response.json();if(!response.ok)throw Error(result.error||'Falha ao parear');$('#pairResult').hidden=false;$('#pairResult').innerHTML=`<strong>SEGREDO MOSTRADO UMA ÚNICA VEZ</strong><pre>node_id: ${safe(result.node.id)}\nnode_secret: ${safe(result.secret)}</pre><p>Configure no <code>runner/config.json</code>. Nunca comite essa credencial.</p>`;e.target.reset();await refresh()}catch(error){$('#nodeError').textContent=error.message}});
$$('.filter').forEach(el=>el.addEventListener('click',()=>{taskFilter=el.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===el));render()}));
const commandChoices=[['overview','Overview','◫'],['create','Nova missão','✦'],['missions','Missões','☷'],['projects','Repositórios','▧'],['nodes','Executores','⌁'],['connections','Integrações','⬡'],['settings','Configurações','⚙']];
function closeCommands(){$('#commandMask').hidden=true;$('#commandInput').value=''}
function filterCommands(){const q=$('#commandInput').value.toLowerCase();$('#commandResults').innerHTML=commandChoices.filter(x=>x[1].toLowerCase().includes(q)).map(x=>`<button class="command-item" data-command="${x[0]}"><span>${x[2]}</span>${safe(x[1])}</button>`).join('')||'<div class="empty">Nenhum comando encontrado.</div>';$$('[data-command]').forEach(x=>x.addEventListener('click',()=>{closeCommands();page(x.dataset.command)}))}
function openCommands(){if($('#app').hidden)return;$('#commandMask').hidden=false;filterCommands();$('#commandInput').focus()}
$('#openSearch').addEventListener('click',openCommands);$('#commandInput').addEventListener('input',filterCommands);$('#commandInput').addEventListener('keydown',e=>{if(e.key==='Enter'){const first=$('[data-command]');if(first)first.click()}});
$('#commandMask').addEventListener('click',e=>{if(e.target===$('#commandMask'))closeCommands()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandMask').hidden?openCommands():closeCommands()}if(e.key==='Escape')closeCommands();if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!$('#app').hidden)page('create')});
setInterval(()=>{if(!document.hidden&&mode==='live')refresh()},30000);
init();
